ca_certificate: |
  -----BEGIN CERTIFICATE-----
  MIIDSzCCAjOgAwIBAgIQHZSJajRSoE3h9yHzlQMYyzANBgkqhkiG9w0BAQsFADAa
  MRgwFgYDVQQKEw9WZWxvY2lyYXB0b3IgQ0EwHhcNMjQwOTI0MTkyNzI5WhcNMzQw
  OTIyMTkyNzI5WjAaMRgwFgYDVQQKEw9WZWxvY2lyYXB0b3IgQ0EwggEiMA0GCSqG
  SIb3DQEBAQUAA4IBDwAwggEKAoIBAQDjEtqoq2m+HBOQijiXpqj7immJ51s5ULjB
  givxnU1xV8BZt0439j+LYIUC876bHbIYk3JpaLcVokcgJzLBQ7XVvl3D5CnhPWMk
  aJR1cC32OhrJ/GuEic1EGFDt/ZdiAITgbFDl8ugFFBtFzp+jZoW1YdaI3iup6jTs
  bvc+rkOXT2vV42uRfqfk9+5/44HlKHSZZgcTNhhudqxnWm9Nz1Kj4Q8xddhoS7o7
  p80uI1xEgzmWlo6ndsJw1jxHo3m1LjCJ026IpJLvISRi4W8VJKiNFwWsEK32F+CM
  +tYhUzoPgpaJOlY1RMgWJjLZOxBI91jyl0JY9zFjlDXcJQFWLWbLAgMBAAGjgYww
  gYkwDgYDVR0PAQH/BAQDAgKkMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcD
  AjAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBQeG9mAsXI6rLLbeWJ1PnvGPyye
  sTAoBgNVHREEITAfgh1WZWxvY2lyYXB0b3JfY2EudmVsb2NpZGV4LmNvbTANBgkq
  hkiG9w0BAQsFAAOCAQEAc9R6+00xeDI5NdUW2xsWQFCUpTW5N9OvPcMkIal3ppT5
  fjpfk6WaBSdAFvw2cRXmb8VWt1vqeDWeA1zX7MjVvcvydhz4dK/+F32xqMjGWatB
  4U33JAo5vHfKK483F0qc+Kkq88+lbsYyYVjtDaq38pvbicxTJYc+NDFlEoZZXD/K
  QyFvPM92+BgBT+qKW4DatUXcEofYZ9aB08wyJDfLXBevJxafQ3btG7vBr9vJQ7fm
  3oNZMwMWx+dtodhDRW3ttV5cXToqX/U68EzIxj6FmrTwhkQbSBC4cTtpOGj7Swxi
  Zq0lGryHyQ8EhKEBTFcGQJ1mlV9Nh05u1MkGUA0YCQ==
  -----END CERTIFICATE-----
client_cert: |
  -----BEGIN CERTIFICATE-----
  MIIDPTCCAiWgAwIBAgIQFABQAwXSFKzXzAb2vxinUTANBgkqhkiG9w0BAQsFADAa
  MRgwFgYDVQQKEw9WZWxvY2lyYXB0b3IgQ0EwHhcNMjQwOTI1MTczNTM3WhcNMjUw
  OTI1MTczNTM3WjAnMRUwEwYDVQQKEwxWZWxvY2lyYXB0b3IxDjAMBgNVBAMTBUJy
  aWFuMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxve3WTUuMdxRcdq3
  ms1XNfWvVHLQ4NFEDkfnaWkuPTaM1ovOsVgMNDZhz2qX2xJkImo34eSmRCubs5iL
  A5ypox4U31Mj2YRYsoQOBzK+hgqo5mmUJsinfrH/w0t7OBYCrLmpUj3vpg6Larj7
  O9iRXy0ihKZSyiZMWyQxYMFwemFjGmaIh79lt4jW9xQhuK0ULkewCoSLb74cVMNx
  c7UM+Jx2G2qosXO0J4nuDp9gkaRu+AAtPxgum1TrBH9INuRkr+cK5TG9/TcjoAMC
  oF8/0BpEVBGM+MFFL1ZyaJjOVSvEDBHkmrnmmdbkAgx76m35qw39jBC3j0JwVTXb
  z+aX6QIDAQABo3IwcDAOBgNVHQ8BAf8EBAMCBaAwHQYDVR0lBBYwFAYIKwYBBQUH
  AwEGCCsGAQUFBwMCMAwGA1UdEwEB/wQCMAAwHwYDVR0jBBgwFoAUHhvZgLFyOqyy
  23lidT57xj8snrEwEAYDVR0RBAkwB4IFQnJpYW4wDQYJKoZIhvcNAQELBQADggEB
  AJTImNW2dgrVylb8XY62pt9twmwT3vP0hmbWrax3SuzzaiJhsXxDkWre08B4tRkQ
  3q5WzIQYOfCiI5ccWxPB+OT1ytse4DolBWol3xkWc4jRSRzcof8Q6xzxf6EmHGOW
  9M5iMfy0C7ngcwG/qZihRGWDJvSdXhBbVeoXT1DhyFULo5HM3eKAKrDIlzeWjb6G
  5v8v1xSPIs3nbrLmVCGZwy8RpNpgGWR1KuGLCIImpLmPdA9EsVS8lGUZYX8xeVR3
  5vTkPufD4Z3ChvUxYcfXMr6uLcSzqZJfPxO7b9RdzUW6Wdf/XtHybQTjyaHJ84fe
  2y7aKU7MtvSLJemQIp7TDrw=
  -----END CERTIFICATE-----
client_private_key: |
  -----BEGIN RSA PRIVATE KEY-----
  MIIEpQIBAAKCAQEAxve3WTUuMdxRcdq3ms1XNfWvVHLQ4NFEDkfnaWkuPTaM1ovO
  sVgMNDZhz2qX2xJkImo34eSmRCubs5iLA5ypox4U31Mj2YRYsoQOBzK+hgqo5mmU
  JsinfrH/w0t7OBYCrLmpUj3vpg6Larj7O9iRXy0ihKZSyiZMWyQxYMFwemFjGmaI
  h79lt4jW9xQhuK0ULkewCoSLb74cVMNxc7UM+Jx2G2qosXO0J4nuDp9gkaRu+AAt
  Pxgum1TrBH9INuRkr+cK5TG9/TcjoAMCoF8/0BpEVBGM+MFFL1ZyaJjOVSvEDBHk
  mrnmmdbkAgx76m35qw39jBC3j0JwVTXbz+aX6QIDAQABAoIBAD5xkAFXR2AunQD2
  e5kByNUOfjAquJNWGd3Bg0b506EydZD/36aY03uvdZL7CR2f7/09CLzEXcoXRY5f
  2YEQscyXrEVKen3Ro2SjPSPVMSYwQkHN8MkbQDXq9zH7hnhbsAs1WYaOGaAsAGVG
  GNL3bOhJ6gNnj6QR0PTprvWGwB4n1JzPOLstLoLZKkCcI1VQHjRWks/gcPUchU9M
  tMHArn6imyAK7jFcrXCUBj19krJ4KDgS9iFnAthY7AjwYrtMaJNM5CD4siYXK8xX
  t2kK3fP6lD0Sq2geniLcXWjizYZ1EiG74biSG1OfDPq7bS93Vba8Ys7goOKBiZNR
  kYggEAECgYEA3kcRZWQqw9LY/XA0Ma66ohPN2jlE4eG8ZfEpNECtxL7dvUAB6FWy
  NkQI2Jt/koTXbK2NfOqlm+sB7aOjHiYGyEAUtcilDImvQnCOmqnMQIcu5xik94ib
  UR8pnNZN+yO1ojle7802BqPTVKx3XpnJCj9eZ49r6kM7M4CDaLLdncECgYEA5SdS
  4LHLrL8Ne86vshZARHGkQ3cx6TY3Jw6kccroaWQ/pWhT9njlDc36ehkpwn/FaHLv
  LSOX3BTYXKVPhdNXPXLXHnkXdTmpte1lBnj8Qem4x2Ff7p65CwvDSM+GyYTe3+vQ
  4m0U5yiRJN6WtWzd03cCzxnGj1L32ksmF5XlVCkCgYEAsO5zG3kjTWMdlIdnFJEY
  QIFxH57shL0SITdY7B379BtWGBnGKvFj/Swkun70imWxsPFpKaECGF112HqkEhCE
  34uasKS5NIS4fDNqYBR+4HJ61DtavSsBLw6WKiCwTBM9tpbiShHYSmrHgqQSFLxn
  Of/9HoQci4neqv1GHOYb4EECgYEAv44fubTmjYEnxFcCh9wR3SUiK0N4dXrcn8md
  rYHwxikHCz4q8d4dm2yT9X0Ta4NjgeySAym9yDukoc2OrE/+nV9idBbFhTiupWXN
  DZwVQwQdco3zo4ULKjCrDjJsegiYRpbaBm0pDBLdQfTQBtj6lcrmjjj9wtGYXuJy
  9URYcAECgYEAr49vu9x7a6djhVnfEaeVyMmItE6D/+oHPINFmcCCAkdpZu+YFJSR
  07HMR52u8GfztKygzaYM52z0wxKGFYVSMMQvgxmIdR47Ol8u3WlV+PkRlcIcLkW/
  Xh2QMkev7LCuTyBZgCz92n0HxuVxi66Tvjbozoks0m1r539du+GDOVw=
  -----END RSA PRIVATE KEY-----
api_connection_string: 192.168.122.236:8001
name: Brian
